### ISSUE TITLE
Add alternative ways of importing title, description, XML metadata

### ISSUE THREAD

**Issue by craigds** [koordinates/sno#102]
importing from GPKG pulls title, description, and XML metadata from `gpkg_contents` and `gpkg_metadata`, but no such thing exists in most other formats.

As we add other import sources, it'd be helpful to have the option to import that metadata in other ways.

I propose:

* `--title="NZ Memorials List"`
* `--description-from=./description.txt`
* `--metadata-from=./metadata.xml`

The description one could also have an inline `--description="This is the description"` variant, but I'm not sure how useful that would be. It wouldn't be very friendly for the XML metadata one.

**Comment by rcoup** [comment]
Seems reasonable.

Could alternatively go curl-styles with `--description=@path/to/my_description.txt` (from-file), `--description=-` (stdin), and `--description="an inline description"`?

`kubectl create configmap` uses some of these sorts of patterns too.

**Comment by olsen232** [comment]
If we have a good pattern for data input like this we can use it in many places -
- commit messages
- conflict resolution data
- everything else, probably

**Comment by craigds** [comment]
curl-style is awesome 👍 are y'all happy to just use that?
