### ISSUE TITLE
sno switch incorrect exit code when branch does not exist

### ISSUE THREAD

**Issue by UberMouse** [koordinates/sno#107]
Currently, `sno switch <branch-that-does-not-exist>` returns an exit code of `2` (`INVALID_ARGUMENT`) instead of the correct exit code of `43` (`NO_BRANCH`).

Not important to fix, I just want it tracked so I can document it in the app code.

**Comment by craigds** [comment]
I'm not seeing this:

```bash
$ sno switch foobarbaz
Error: Branch 'foobarbaz' not found.
$ echo $?
43
```

What output are you getting?

**Comment by UberMouse** [comment]
Oh, it's probably been fixed in a newer version than I have. It was documented as being broken in confluence and that matched what I was seeing. I'll close this then.

**Comment by craigds** [comment]
okay, thanks. I'm using an unreleased version and most of the custom exit codes were added since 0.3.1. So 0.4 should fix this when released 👍

**Comment by olsen232** [comment]
Sorry, I didn't keep that wiki page very up to date... I should have used the issue tracker
