### ISSUE TITLE
Add a `help` subcommand

### ISSUE THREAD

**Issue by craigds** [koordinates/sno#127]
We need to make docs easier to access as well as easier to update. Having them in a github wiki is _okay_ but:

 * it's hard to keep doc changes in sync with code changes (i.e. they're not included in PRs)
 * they're not available from the command-line
 * there's no possibility of auto-generating any documentation; it's all manual point-and-click editing

We should create a proper docs build with restructuredtext and sphinx, to build man pages and expose them via `sno help <subcommand>`, as well as build them into a readthedocs site, or similar.

**Comment by olsen232** [comment]
Would `sno help <subcommand>` do the same as `sno <subcommand> --help`?

Seems like it should - having two different help pages exposed at two very similar commands seems confusing and redundant. But, it might be hard to control the behaviour of built-in click option `--help`

**Comment by craigds** [comment]
yes I think it should do the same job. We can remove the click builtin `--help` option with 

```
@click.command(add_help_option=False)
def cli(...):
```

**Comment by rcoup** [comment]
I think having both assists users TBH, even if one is displayed/recommended (`sno help <command>`?) and the other just works.

I hate having to figure out the syntax for getting help, since I'm really trying to figure out the syntax for _something else_!

**Comment by craigds** [comment]
^ #221 adds the `help` command, but it's just a synonym for `--help`. The other docs changes can wait for a later date.
