### ISSUE TITLE
Make feature names (or meta item names) consistent across commands

### ISSUE THREAD

**Issue by olsen232** [koordinates/sno#134]
Background:

The original command that had names for features was `sno diff`.
If you wanted to specify a single feature to see a diff of it, that looked like this:
`sno diff HEAD <dataset>:<pk>`
And the resulting output would have the following heading:
`<dataset>:fid=<pk>`

This gave us two different forms for feature names already.
`sno conflicts` and `sno resolve` also needed names for features, but with the added complexity that they also needed names for non-features - ie, meta items. The names had to be consistent when listing conflicts and when specifying conflicts. `sno conflicts` also a) places conflicts in a hierarchy and b) sometimes needs to name conflicts such that some part of their name actually has multiple values. This resulted in the following names for conflicts / features / meta items:
`<dataset>:feature:<pk>` conflict involving single feature
`<dataset>:feature:ours=<pk1>,theirs=<pk2>` conflict involving two features
`<dataset>:meta:<meta_path>` conflict involving meta item
`ours=<dataset1>,theirs=<dataset2>:feature:pk` conflict involving two datasets

Some of these conflicts are fairly theoretical and we hope not to encounter them too often.
Especially the highly theoretical `<dataset>:ours=meta,theirs=feature:...`
Nevertheless, the structured way of categorising every piece of data as `<dataset>:<feature|meta>:<feature_pk_or_meta_path>` means that we can handle arbitrary conflicts and that every conflict has a place to be within a hierarchy - ie, a JSON tree.

Since then, `sno diff`, `sno commit` and `sno conflicts` support filtering by providing filters in any of the following forms: `<dataset>`, `<dataset>:<pk>` or `<dataset>:feature:<pk>` 

To do:
- Make sure everything that names features or names the parts of a dataset, use a consistent naming scheme. Probably this involves changing sno diff to use `<dataset>:feature:<pk>` instead of `<dataset>:fid=<pk>`, but open to ideas.
- `<dataset>:<pk>` should be allowed as an alias for `<dataset>:feature:<pk>` when accepting user input.
- When commands have JSON output which is a tree of JSON objects, this naming scheme should be used to place data appropriately in the tree . Eg the top level dict in sno diff should be table names, the next level should be feature or meta, the next level should be primary key or meta_path. Command specific names likes "featureChanges" should not be used.
- Decide on a naming scheme for features which have multiple primary keys. Note that when there are multiple primary keys, these have an order, so we just need a delimiter between the primary keys eg `<dataset>:feature:<pk1>:<pk2>` if `:` is appropriate.

**Comment by rcoup** [comment]
Sounds good to me.

> Note that when there are multiple primary keys, these have an order, so we just need a delimiter between the primary keys eg `<dataset>:feature:<pk1>:<pk2>` if `:` is appropriate.

Re-using the same delimiter prevents referring to anything deeper in future (eg. an attribute, or a band of a raster object) so maybe another separator (`;,+|$#^~`?) is better? We could use `%` or `\` escaping to deal with clashing delimiters occurring in string PK fields, and we probably need to escape `\n`/`\t`/` `/etc as well.

I guess escaping `:` could apply to dataset identifiers too if we allow it in future (but I'm tempted not to, they'll inevitably end up in file paths somehow and Windows has so many special file-path behaviours).

**Comment by olsen232** [comment]
This is mostly done except for handling multiple primary key fields, which we should track separately
