### ISSUE TITLE
Simplify repo versioning

### ISSUE THREAD

**Issue by olsen232** [koordinates/sno#142]
Right now, every dataset in a repo stores its own version in a blob `<dataset>/meta/version`.
In addition to this, the working copy stores its version in the git config file:
```
[sno "workingcopy"]
	version = 1
	path = example.gpkg
```

This seems like too many versions:
- There is no plan to actually support multiple dataset versions in a single repository - for this to make sense, sno v0.5 or later would have to actually support interacting with more than one dataset version (but the plan is actually to delete obsolete code, as happened to v0), and to end up with mixed version repositories, we would have to upgraded some but not all of a repository's contents (also not planned - currently a migration creates a fresh repository with only latest-version content).

- Dataset versions and working copy versions are likely tied together. For instance, datasets v2 will need working copies that support multiple primary keys. Potentially there could be some backward compatibility between certain dataset versions or certain working copy versions, but again, to actually make use of this cross-compatibility, we would need to make certain sno versions simultaneously support multiple versions, which is probably not the plan. 

More concretely:
Imagine that datasets v2 is compatible with both working copy v1 and working copy v2. This makes our lives as developers easier since we can develop working copy v2 without changing datasets v2. However, assuming the latest version of sno only supports the latest version of each (which is the plan as far as I know), there is no real user benefit to this cross compatibility: they still have to have the latest version of each, and if they don't have that, they just need to run the upgrade command.

## Proposal:
- Store a single sno version in the git config file.
- Make this the same as the version of sno eg "0.5" (for the next version), or, make it the lowest of the set of compatible versions (eg "0.0" for "0.0"-"0.1", "0.2" for "0.2"-"0.4", "0.5" for "0.5"-something)
- Make the upgrade command just read the repo version, then use this to upgrade everything to its native version - presumably, the only version that is still supported (except by the upgrade command itself)

No need for commands to accept a `--version` option or to read the repo version except to check it is the expected version that is supported by this version of sno. If not, they simply abort with instructions of how to upgrade the repo.

Versions older than 0.5 would be recognised not by this version number, but by the currently applicable heuristics (eg, find any dataset in the repo and check its version number - if it is "1.0", then repo version can be inferred as "0.2")

**Comment by rcoup** [comment]
> This seems like too many versions:

yes 👍 

> There is no plan to actually support multiple dataset versions in a single repository

Yeah, repo should all be one version realistically.

> Dataset versions and working copy versions are likely tied together. 

Yep.

> Store a single sno version in the git config file.

git config is local though, so how do we tell what version a pulled/pushed repo is? Feels like it needs to be in the repo as an object(/ref/note/something)?

**Comment by olsen232** [comment]
This is done except for the related bug:

upgrade: Don't require versions to be specified - https://github.com/koordinates/sno/issues/169
