### ISSUE TITLE
Support custom WKT for CRS definitions

### ISSUE THREAD

**Issue by olsen232** [koordinates/sno#148]
Datasets v2 currently assumes all WKT definitions will have an authority, which it uses as their name. In theory, this is a problem, since a user-defined SRS might not have any authority.

Datasets v1 doesn't explicitly have this requirement, but all the same it's not clear that v1 actually supports anything that v2 does not. During imports with custom definitions that *do* have an authority set, the importer ignores the WKT and just uses the official definition for that authority, which is presumably hard-coded in the import library. Imports with custom definitions where the authority is not recognised seem to fail. This is due to the GDAL library we are using, and how we are using it (ie, we could work around it).

We should take some custom WKT definitions that we want to support and make sure we can preserve them through the import library properly. Until this is done, there's not much point finessing the SRS conversion code in v1 or v2, as long as it works for everything we can actually import - ie, definitions with authorities.

**Comment by rcoup** [comment]
Having no CRS at all is pretty common in the GIS world (basically a user only ever works in one CRS and that is their default so it never gets properly assigned/saved).

@craigds maybe we add a trivial SHP-without-prj import test case, since they're the main culprits?

**Comment by edcorkery** [comment]
It's also common enough to have a custom SRS for big projects, e.g. for an expressway or dam build, especially at America's vast geographic scales. But this would normally be private internal data only. I don't think we've ever run into any on mapping agency or county websites we've scraped.

**Comment by olsen232** [comment]
Changed title to be more self-explanatory

Detail: we may already have some support for custom WKT CRS definitions, but we still need to do an audit to work out what works and what doesn't.
