### ISSUE TITLE
Add a `schema` command

### ISSUE THREAD

**Issue by craigds** [koordinates/sno#153]
We need a way for diff users to interpret the diffs they're given, without having to consult the working copy.

In particular, since we ditched GeoJSON for json diffs, it can be unclear what the primary key and geometry fields are, because all fields are lumped together in feature objects.

I propose a `schema` command which would show us the schema of a layer (or all layers) at a particular revision (by default HEAD)

```bash
# show schemas of all layers at HEAD
sno schema
sno schema HEAD

# show schema of one layer at HEAD
sno schema HEAD nz_pa_points_topo_150k

# show schema of one layer at another rev
sno schema abcd1234 nz_pa_points_topo_150k
```

The output could look something like this (with `-o json`):
```json
{
    "sno.schema/v1": {
        "nz_pa_points_topo_150k": {
            "primaryKeyFields": ["id"],
            "fields": [
                {
                    "name": "shape",
                    "type": "GEOMETRY",
                    "subtype": "polygon",
                    "nullable": true
                }
            ]
        }
    }
}
```

Current sno doesn't support schema changes, so all revisions will show the same schema, but that will change with dataset v2 and presumably sno 0.5, so it makes sense to bake revision support in there.

**Comment by olsen232** [comment]
datasets v2 stores a schema internally that is already json. Should we use that? Having to convert it to anything else would a) be more work and b) might indicate that the its model is not quite right.

Anyway it is here:
https://gist.github.com/rcoup/2774c12af9f3997088dd13a8a84eff98#file-schema-js

**Comment by craigds** [comment]
looks good to me. cc @UberMouse

**Comment by UberMouse** [comment]
LGTM

**Comment by craigds** [comment]
Just realised most of this information is already available in a less-convenient form in `sno meta get <datasetname>`

**Comment by olsen232** [comment]
@craigds what are your thoughts - what is still required here?

`sno meta get <datasetname> schema` shows the schema at HEAD.

- Do we want a schema command to do the same thing?
- Do we want the schema command to be able to work at other commits, not just HEAD?
- Do we want sno meta get to work at other commits?

**Comment by craigds** [comment]
Yeah I think this can be closed.

The initial use case where this came up was applying a patch, which is something you always do at HEAD. If we separately find that`meta get` needs to support other revisions for other reasons we can tackle that separately
