### ISSUE TITLE
datasetV2 checkout is very slow

### ISSUE THREAD

**Issue by craigds** [koordinates/sno#159]
`sno -v checkout` on a largeish v1 dataset (2M polygon features) is much slower than the equivalent v1 dataset.

### 1. `dataset.feature_count()` is very slow in v2.

```
# v1 - initial feature count took 3s
Jul 09 12:00:07 INFO:WorkingCopy_GPKG_1.write_full:Creating features...
Jul 09 12:00:10 INFO:WorkingCopy_GPKG_1.write_full:0.4% 10000/2272386 features... @2.9s (+2.9s, ~17095 F/s)

# v2 - initial feature count took 5 *minutes* (!)
Jul 09 12:03:46 INFO:WorkingCopy_GPKG_1.write_full:Creating features...
Jul 09 12:09:05 INFO:WorkingCopy_GPKG_1.write_full:0.4% 10000/2272347 features... @319.6s (+319.6s, ~156 F/s)
```

### 2. feature iteration during checkout is 3-4x slower in v2:

```
# v1
Jul 09 12:01:58 INFO:WorkingCopy_GPKG_1.write_full:Added 2272386 features to GPKG in 110.5s
Jul 09 12:01:58 INFO:WorkingCopy_GPKG_1.write_full:Overall rate: 20572 features/s

# v2
Jul 09 12:16:12 INFO:WorkingCopy_GPKG_1.write_full:Added 2272347 features to GPKG in 746.9s
Jul 09 12:16:12 INFO:WorkingCopy_GPKG_1.write_full:Overall rate: 3042 features/s
```

note: 746.9s includes the feature count time of 319s. So actual iteration time is 427s, for an *actual* rate of ~5300 features/s. Hence why I said v2 is 3-4x slower.

**Comment by craigds** [comment]
I've done some profiling and found out that `blob.data` is >4x as slow in v2 repos as it is in v1 repos, at least for the NZ property titles repo.

Profiling script: https://gist.github.com/craigds/52574a9413fb70175461241f34cf6f7f

### v2 results:
```
~/layer-50804-v2 (BARE:master) $ /Users/cdestigter/c/sno/profile-blob-data.py . 1000000
         8057895 function calls (3028958 primitive calls) in 138.234 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000  138.234  138.234 <string>:1(<module>)
6028943/1000006    2.729    0.000    2.945    0.000 profile-blob-data.py:23(find_blobs_in_tree)
  1000000  134.577    0.000  134.577    0.000 profile-blob-data.py:31(get_data)
        1    0.711    0.711  138.234  138.234 profile-blob-data.py:35(read_everything)
        1    0.000    0.000  138.234  138.234 {built-in method builtins.exec}
  1028947    0.215    0.000    0.215    0.000 {built-in method builtins.isinstance}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
        1    0.000    0.000    0.000    0.000 {method 'peel' of '_pygit2.Reference' objects}
```

### v1 results:
```
~/layer-50804 (BARE:master) $ /Users/cdestigter/c/sno/profile-blob-data.py . 1000000
         7057966 function calls (3028990 primitive calls) in 33.136 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000   33.136   33.136 <string>:1(<module>)
5028981/1000005    2.319    0.000    2.496    0.000 profile-blob-data.py:26(find_blobs_in_tree)
  1000000   30.101    0.000   30.101    0.000 profile-blob-data.py:34(get_data)
        1    0.539    0.539   33.136   33.136 profile-blob-data.py:38(read_everything)
        1    0.000    0.000   33.136   33.136 {built-in method builtins.exec}
  1028980    0.177    0.000    0.177    0.000 {built-in method builtins.isinstance}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
        1    0.000    0.000    0.000    0.000 {method 'peel' of '_pygit2.Reference' objects}
```


* The objects/ folder seems similar in both repos.
* I created the v2 repo via `sno upgrade 02-05 ...`
* There were loose objects in the v2 repo after upgrade (?) but I removed them via `git repack -Ad` and `git prune` and now both repos are fully packed.

**Comment by craigds** [comment]
@rcoup do you have any ideas about what could cause this?

**Comment by rcoup** [comment]
> There were loose objects in the v2 repo after upgrade (?) but I removed them via git repack -Ad and git prune and now both repos are fully packed.

So the per-call difference is 30µs vs 135µs here...

1. Not that I'd expect much/any difference, but can you try `git repack -adfb`? — the `-f` will recalculate deltas in the pack from scratch. 
2. If you run it for _all_ features, does it show the same difference? Ie. isn't related to feature/object ordering in the repo?

**Comment by craigds** [comment]
> git repack -adfb

that actually solved it (!?)

results, for all 2M features with varying dataset versions / repack levels:

### v1

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000   42.168   42.168 <string>:1(<module>)
11427806/2272404    4.649    0.000    4.923    0.000 profile-blob-data.py:26(find_blobs_in_tree)
  2272403   36.089    0.000   36.089    0.000 profile-blob-data.py:34(get_data)
        1    1.156    1.156   42.168   42.168 profile-blob-data.py:38(read_everything)
        1    0.000    0.000   42.168   42.168 {built-in method builtins.exec}
  2338199    0.274    0.000    0.274    0.000 {built-in method builtins.isinstance}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
        1    0.000    0.000    0.000    0.000 {method 'peel' of '_pygit2.Reference' objects}
```

### v2, immediately after `sno upgrade 02-05`

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000  310.985  310.985 <string>:1(<module>)
13699908/2272355    6.139    0.000    6.593    0.000 profile-blob-data.py:26(find_blobs_in_tree)
  2272354  302.873    0.000  302.873    0.000 profile-blob-data.py:34(get_data)
        1    1.519    1.519  310.985  310.985 profile-blob-data.py:38(read_everything)
        1    0.000    0.000  310.985  310.985 {built-in method builtins.exec}
  2338152    0.455    0.000    0.455    0.000 {built-in method builtins.isinstance}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
        1    0.000    0.000    0.000    0.000 {method 'peel' of '_pygit2.Reference' objects}
```
### v2, after `git repack -ad`

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000  300.410  300.410 <string>:1(<module>)
13699908/2272355    5.775    0.000    6.150    0.000 profile-blob-data.py:26(find_blobs_in_tree)
  2272354  292.837    0.000  292.837    0.000 profile-blob-data.py:34(get_data)
        1    1.423    1.423  300.410  300.410 profile-blob-data.py:38(read_everything)
        1    0.000    0.000  300.410  300.410 {built-in method builtins.exec}
  2338152    0.376    0.000    0.376    0.000 {built-in method builtins.isinstance}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
        1    0.000    0.000    0.000    0.000 {method 'peel' of '_pygit2.Reference' objects}
```

### v2, after `git repack -adf`

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000   44.431   44.431 <string>:1(<module>)
13699908/2272355    5.022    0.000    5.339    0.000 profile-blob-data.py:26(find_blobs_in_tree)
  2272354   37.952    0.000   37.952    0.000 profile-blob-data.py:34(get_data)
        1    1.140    1.140   44.431   44.431 profile-blob-data.py:38(read_everything)
        1    0.000    0.000   44.431   44.431 {built-in method builtins.exec}
  2338152    0.317    0.000    0.317    0.000 {built-in method builtins.isinstance}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
        1    0.000    0.000    0.000    0.000 {method 'peel' of '_pygit2.Reference' objects}
```

### v2, after `git repack -adfb`
```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000   43.882   43.882 <string>:1(<module>)
13699908/2272355    5.004    0.000    5.310    0.000 profile-blob-data.py:26(find_blobs_in_tree)
  2272354   37.418    0.000   37.418    0.000 profile-blob-data.py:34(get_data)
        1    1.153    1.153   43.882   43.882 profile-blob-data.py:38(read_everything)
        1    0.000    0.000   43.882   43.882 {built-in method builtins.exec}
  2338152    0.307    0.000    0.307    0.000 {built-in method builtins.isinstance}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
        1    0.000    0.000    0.000    0.000 {method 'peel' of '_pygit2.Reference' objects}
```

`git repack -adf` provided the biggest wins, but also took 11 minutes to run.

@rcoup can you explain why this might make such a big difference? I'm pretty lost at this point - given that all the objects were already in a packfile, and there's only one commit in the repo, I don't really understand what it means to 'recalculate all the deltas'.

Should we be running `git repack -adfb` during the `upgrade` command? Means quite a large slowdown for the upgrade process.

**Comment by craigds** [comment]
Looks like we could alternatively run `git gc -f`, which does the same thing. We're already running `git gc` during upgrade.

**Comment by rcoup** [comment]
Q: What's special about this repository/dataset?

> Looks like we could alternatively run git gc --aggressive, which does the same thing. We're already running git gc during upgrade.

`git-gc` calls `git-repack` internally 🤷  But it does use different default settings (`gc.aggressiveDepth` & `gc.aggressiveWindow`)

In a packfile, an object is either stored as a compressed whole or as a difference from some other object (ie. a delta). Deltas can be deltas on top of other deltas too. If the layout/options are wrong then it generates larger deltas than necessary, or multi-level-deltas that are less efficient.

[`git-pack-objects`](https://git-scm.com/docs/git-pack-objects): Seems like for us, because we have no incremental object changes, a low `depth` but lots of `window/window-memory` might achieve a good outcome?

Additionally, feels like since we can control the order of features during an import then we can make sure we're basically achieving the same outcome on the first pass by following the sorting order described in [window](https://git-scm.com/docs/git-pack-objects#Documentation/git-pack-objects.txt---windowltngt). 

Not sure if [`threads=0`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-packthreads) is enabled by default in our Sno-wide gitconfig, but it probably should be.

**Comment by rcoup** [comment]
`repack -ad` doesn't really do anything except put everything in a single packfile and drop any disconnected objects. But after an import we'll likely already _have_ a single packfile, and shouldn't have any disconnected objects.

**Comment by craigds** [comment]
Thanks. I'm starting to understand now

So, immediately after the `sno upgrade`, the v2 repo has this:

```
$ git verify-pack -v objects/pack/pack-*.idx

...
non delta: 122023 objects
chain length = 1: 55630 objects
chain length = 2: 55104 objects
chain length = 3: 54577 objects
chain length = 4: 54015 objects
chain length = 5: 53493 objects
chain length = 6: 52975 objects
chain length = 7: 52433 objects
chain length = 8: 51927 objects
chain length = 9: 51430 objects
chain length = 10: 50932 objects
...
chain length = 49: 34989 objects
chain length = 50: 34685 objects
```

This is not the case _before_ upgrade; the max chain length was 3. Seems apparent this is the cause of the slowness... There's clearly a space/speed tradeoff when storing objects as deltas.

So... AFAIU:

Increasing window size will:
 * take more memory 👎 
 * make it more likely that deltas are found with lower depth 👍 

Decreasing depth will (to a point) reduce the impact that deltified objects can have on performance.

I tried increasing window size to 10000, and my `git gc` started taking 1000% CPU for a good 40 minutes before I killed it.  I expect there's a secondary effect where having too _large_ a window means the delta computation has to do too much work, and thus actually slows down the packing.

I tried just a couple different values of `--depth` in the `fast-import` invocation, to avoid creating all these long chains to begin with, and ended up with:

`--depth=10`: ~11000 F/s during checkout (~100% speedup)
`--depth=0`: ~19000 F/s during checkout (~250% speedup)

`--depth=0` uses about 10% more disk than the original (`--depth=50`).

So I think that's probably the solution: Just don't produce deltas at all.

**Comment by craigds** [comment]
It's also much faster (~5 minutes to do the upgrade instead of ~9) so I think it's a win all around

**Comment by rcoup** [comment]
For curiosity, could you do `--depth={1..10}`? I'm wondering if `1` or `2` might get you the 10% space _with_ the speed as well...

**Comment by craigds** [comment]
#163 solved this - checkout perf is as good as v1 now
