### ISSUE TITLE
upgrade: Don't require versions to be specified

### ISSUE THREAD

**Issue by craigds** [koordinates/sno#169]
`sno upgrade 02-05 frompath topath` isn't super great, because users probably don't know or care what version numbers their repo supports.

We should detect the version number from the repo (we have a `.sno-format` file now) and run the appropriate upgrade script(s) to get to the latest version. There doesn't seem to be much point in allowing an upgrade to any _older_ version, so we should just make it:

`sno upgrade frompath topath`

**Comment by rcoup** [comment]
> We should detect the version number from the repo (we have a .sno-format file now)

As long as it works for older stuff as well, sure 👍
