### ISSUE TITLE
upgrade: Linux build has no upgrade scripts

### ISSUE THREAD

**Issue by craigds** [koordinates/sno#172]
PyInstaller doesn't find the magic imports for `sno/upgrade/upgrade_02_05.py` etc, so the linux build doesn't have them. So the upgrade command doesn't have any subcommands:

```
$ sno upgrade --help
Usage: sno upgrade [OPTIONS] COMMAND [ARGS]...

  Upgrade repositories between versions of Sno

Options:
  --help  Show this message and exit.
```

_probably_ the easiest solution is to just import all the subcommands normally from `__init__.py` explicitly

**Comment by rcoup** [comment]
Did you figure out why it's _only_ Linux?

Solution is fine, fwiw could also add to the PyInstaller spec file explicitly.

**Comment by craigds** [comment]
ah well I only tested on linux and mac, and only the dev version on mac (so no pyinstaller involved). 

This would have been a problem for Windows as well.

**Comment by craigds** [comment]
Yep I looked at adding it to `hiddenimports` in the spec file, but decided it was simpler just to simplify the command so it didn't need extra handling
