### ISSUE TITLE
Automatically create working copy on import

### ISSUE THREAD

**Issue by olsen232** [koordinates/sno#192]
- `sno init` won't create a working copy, but it will store a default working copy location and working copy version in the repo config.
- `sno init --workingcopy-path=some_path --workingcopy-version=some_version` will override the defaults
- `sno init --bare` will create a repo which never has a working copy

The following commands all update the working copy. If no working copy is present (as happens on the first import), one will be automatically created using the info in the repo config:
- `sno import`
- `sno checkout`, `sno switch`, `sno reset`

**Comment by craigds** [comment]
is this done? I see de663b3685d7f1af7f166c031e1384c34d3f036b is in master.

Probably `upgrade` should also create a working copy, if there was one before the upgrade. At present it doesn't.
