### ISSUE TITLE
Add a way to list datasets

### ISSUE THREAD

**Issue by craigds** [koordinates/sno#203]
It'd be helpful to have a way of listing datasets.

`sno meta get` requires a dataset name as an argument. Other commands can optionally take dataset names for filtering (`sno diff` for example).

But there's no easy way of finding out what the valid names are, especially if you don't have a working copy handy.

We probably should:

- add a command to list datasets (`sno datasets` / `sno datasets list` ?)
- automatically list the datasets in the usage info when you run `sno meta get` without arguments.

**Comment by olsen232** [comment]
Rob and Hamish voted `sno data ls`

**Comment by UberMouse** [comment]
Fixed in #216
