### ISSUE TITLE
Last chance to rename various things in v2

### ISSUE THREAD

**Issue by olsen232** [koordinates/sno#215]
Soon datasets v2 will be (more-or-less) finished and presumably we will release a version 0.5

We can make a lot of breaking changes as we move to V2 that we will be stuck with for a long time afterwards, unless we want to write more upgrade scripts. So, I'm making a list of things we might want to change before it's too late so that our interface and maybe even our internal format is tidy and makes sense.

### schema -> schema.json
Currently part of the public interface since we show meta-items by name during diffs.
We also store JSON metadata in meta-items, and those ones *do* have a .json suffix - we should be consistent.

### .sno-format -> .sno.repository.version (or similar)
We don't call it "format" anywhere else except for this one file - all through the code it is the repo version, the dataset version, or the structure version, and it is specified with "--version". 
Name options:
"sno.repository.version" is consistent with existing sno variable "sno.workingcopy.version"
"sno.repositoryFormatVersion" is consistent with existing git variable "core.repositoryFormatVersion"

### .sno-table -> .sno-dataset 
since we call these "datasets" everywhere else.

### add sno.repository.version to the repo config:
ie add a config variable that contains the same information as the "sno.repository.version" file.
The reason for having both ways of storing it is that
a) Why in the repo config: ideally we would already know if a sno repository is V1 or V2 even before it has any commits (unless we decide to create repositories with an initial commit just to save the version number).  Right now we don't know if we have a V1 or a V2 repository until we import the first dataset, which doesn't make as much sense: it means the first import command gets to choose the version, and the second one has to be the same as the first.
b) Why as a committed file: so that cloning a repository will also clone the "sno.repository.version" file, which doesn't happen with repo config

### remove sno.workingcopy.version from the repo config
If this is missing, we should assume that sno.workingcopy.version is the same as the repo version.
Or stricter: sno.workingcopy.version could be ignored even if it is present, and the workingcopy version is always the same as the repo version.

**Comment by olsen232** [comment]
== Filenames
=== srs/EPSG:1234.wkt -> crs/EPSG:1234.wkt

From @rcoup 's comment on https://github.com/koordinates/sno/pull/213 - CRS is now the standard name for this in OGC

**Comment by craigds** [comment]
on board with all of this.

>  Or stricter: sno.workingcopy.version could be ignored even if it is present, and the workingcopy version is always the same as the repo version.

this - there's no reason to have them be different, as long as we make this change by 0.5


Additionally I think we should

 * change the version flag to `--repo-version` while we're at it? `--version` already has a purpose in basically every command ever written.
 * add the flag to the `init` command. Probably hide or remove it in the `import` command.
 * make 2 the default version; there's no reason to release a 0.5 which still creates v1 repos by default

**Comment by rcoup** [comment]
LGTM

**Comment by rcoup** [comment]
.sno-table -> .sno-dataset

Had a second thought about this — originally my concept was that rasters/point-clouds/etc may be handled via different structures. But I guess they could all sit under .sno-dataset as well without too much issue? 😄

**Comment by olsen232** [comment]
Discussed offline, keeping .sno-dataset for now. We still have a lot of options how we extend this in the distant future

**Comment by olsen232** [comment]
Committed as:
01c1ccb9f8e77ad67c434695a0693b46df2f5d7d
324b05911ad3f0ccb9e6125f6e6327eb236ea1bc
fac8d9d06038d457f61ae24abb5806e481a6950f
8c3cb23131c2421954a192425814f77ffe65189e
