### ISSUE TITLE
Patches which create or delete datasets are not yet supported

### ISSUE THREAD

**Issue by olsen232** [koordinates/sno#239]
Some assumptions have not been changed since V1:
- every patch is assumed to apply to an existing dataset
- every working copy change is assumed to apply to an existing dataset - ie, we do not handle the user creating tables or deleting tables in the working copy

- as a result, the only way to create a dataset is using the `sno import` command, just as in datasets V1.
- and there is no way to delete datasets at all.

**Comment by rcoup** [comment]
Should (2) & (4) become new issues?
