### ISSUE TITLE
commit/apply creates loose objects

### ISSUE THREAD

**Issue by craigds** [koordinates/sno#247]
commits created with `RepositoryStructure.commit()` (ie `commit`, `apply` commands) appear to create loose objects, rather than writing to packfiles. i.e. each feature and tree becomes a real file on disk.

AFAICT the [odb backends](https://www.pygit2.org/repository.html#the-odb-class)} are set up correctly; the first backend in the list is a pack backend.

However, `create_blob()` and `TreeBuilder.write()` actually call `git_odb_stream_write`/`git_odb_write` respectively. Neither of those methods actually writes to packfiles.

I can't find any docs on this, but I suspect we need to use a [packbuilder object](https://libgit2.org/libgit2/#HEAD/group/packbuilder). Unfortunately those aren't exposed in pygit2, so we'd need to figure out how to expose them first.

As a workaround in the meantime, perhaps `RepositoryStructure.commit` should be calling something like `git repack --depth=1 -d -q` to repack all the objects into a pack file.

**Comment by rcoup** [comment]
Packing is relatively slow, we don't want to do it with tiny commits (which in _normal_ editing use cases is most of them), so feels like maybe we want to:

* Run `git gc --auto` after each commit/apply operation
* Tweak the `gc.auto` configuration default

> **`gc.auto`**
When there are approximately more than this many loose objects in the repository, `git gc --auto` will pack them. Some Porcelain commands use this command to perform a light-weight garbage collection from time to time. The default value is 6700.

**Comment by craigds** [comment]
From noticing very poor performance in repos after applying multiple ~20000-feature patches, I'd say 6700 is _probably_ a fine default.

**Comment by craigds** [comment]
this was handled by #250
