### ISSUE TITLE
Quick Guide instructions don't work (on Windows10)

### ISSUE THREAD

**Issue by iharrison** [koordinates/sno#248]
Following the first instruction on https://github.com/koordinates/sno/wiki/Quick-Guide doesn't work.

Where there's a GPKG in C:\Temp\sno_test\my.gpkg
```
C:\Temp\sno_test>sno init --import GPKG:my.gpkg
Error: Invalid value for directory: "C:\Temp\sno_test" isn't empty
```
Where directory C:\Temp\sno_test\ is empty
```
C:\Temp\sno_test>sno init --import GPKG:my.gpkg
Error: Couldn't find 'my.gpkg'
```

OS is Windows 10
```
C:\Temp\sno_test>sno --version
Sno v0.5.0, Copyright (c) Sno Contributors
» GDAL v3.0.4; PROJ v6.2.1
» PyGit2 v1.1.0; Libgit2 v0.99.0; Git v2.25.1.windows.1
» APSW v3.31.1-r1; SQLite v3.31.1; SpatiaLite v5.0.0-beta0; Libpq v11.0.3
» SpatialIndex v1.8.5
```

**Comment by craigds** [comment]
Thanks for trying out sno!

How do [these changes](https://github.com/koordinates/sno/wiki/Quick-Guide/_compare/17876b22656e94c63c4d32fe617bd4bbcd879bdc...278be30809213879fc6d07a7a38adc66de15c5a4) look? Feel free to suggest more.

**Comment by iharrison** [comment]
Looks good thanks Craig.
