### ISSUE TITLE
`sno switch [branch]` doesn't switch to upstream branch if it exists

### ISSUE THREAD

**Issue by hamishcampbell** [koordinates/sno#259]
Given a remote `origin` with a branch `other-branch`, the following command does not currently work as expected:

```
$ sno switch other-branch
Error: Branch 'other-branch' not found.
```

To check out a remote branch and configure tracking, it seems you currently have to do something like this:

```
$ sno switch origin/other-branch
$ sno switch -c other-branch
$ sno push --set-upstream origin other-branch
```

I expected `sno switch other-branch` do to this for me. That is:

1. Look for a remote branch with the name `other-branch`
2. check that branch out
3. configure the upstream source

**Comment by rcoup** [comment]
👍  needs to match [git's behaviour](https://git-scm.com/docs/git-switch)
