### ISSUE TITLE
CRS's are treated as being authority-less when they have an authority

### ISSUE THREAD

**Issue by olsen232** [koordinates/sno#278]
Sno generally respects the user's choice to supply whatever CRS they want, and to call it what they want.
It tries to store it at a path based on the authority eg `crs/EPSG:2193.wkt`.

There is also code for generating a name or CRS id in the case where no authority is provided. This code is supposed to be exercised rarely since, in practise, almost every WKT has an authority. However, a bug in the way we use osgeo.osr.SpatialReference means that we are losing authority data and generating CRS ids much more often than we should.

Arcgis Pro deals poorly with these custom CRS ids - once we have fixed the authority parsing code, we may still need to revisit how we generate custom CRS ids, figure out what exactly Arcgis pro doesn't like.

**Comment by olsen232** [comment]
Fixedish - we're now pretty good at parsing authorities.

Existing repositories can still have problems caused by this - v2 repositories can have the CRS definition stored at a stupid path eg `CUSTOM:12345678` instead of `EPSG:2193` - which happily at least doesn't affect the working copy - and v1 repositories can have a bad srsid in `meta/gpkg_spatial_ref_sys`, which does affect the working copy.

If we can make sure mirroring (which is always V2) isn't affected by either of these bugs (eg, remirror the last revision of any repos that have bad CRS ids) then things should be mostly fixed. Leaving this bug open to track any further issues.

**Comment by rcoup** [comment]
wild-guess: numbers bigger than six digits cause problems in Arc*
