### ISSUE TITLE
`--dataset-changes` returns `[]` for shallow clones

### ISSUE THREAD

**Issue by craigds** [koordinates/sno#288]
After cloning a repo with `--depth=1` I get this:

```
$ sno log -1 -o json --dataset-changes
...
    "datasetChanges": []
```

... for a change which definitely changed a dataset

**Comment by craigds** [comment]
this is confusing, but @rcoup pointed out this is all you can really expect from git. There's no previous tree to compare to in this case, so we can't determine what datasets were changed.

Perhaps the only correct behaviour would be to list _all_ the datasets rather than an empty list. That's consistent with git's behaviour with `--stat` which lists _everything_.

**Comment by olsen232** [comment]
Fixed at https://github.com/koordinates/sno/commit/fd2d0f72d9cae60a46b6147da69910352a79b3d7
