### ISSUE TITLE
`sno init --bare` makes a repo with a nonbare-like structure

### ISSUE THREAD

**Issue by craigds** [koordinates/sno#303]
Trying to create an empty bare repo:

```
$ sno init --bare x.git
Initialized empty Git repository in /Users/cdestigter/x.git/.sno/
Created an empty repository at /Users/cdestigter/x.git — import some data with `sno import`
```

the repo is successfully bare:
```
$ git -C x.git config core.bare
true
```

Unexpectedly though, there is an internal `.sno` folder and `.git` link, just like a non-bare repo:

```
$ ls -lha x.git
total 4.0K
drwxr-xr-x    4 cdestigter  128 Nov 11 15:13 .
drwxrwxr-x+ 231 cdestigter 7.3K Nov 11 15:13 ..
-rw-r--r--    1 cdestigter   13 Nov 11 15:13 .git
drwxr-xr-x   10 cdestigter  320 Nov 11 15:13 .sno
```

This repo layout can't be served by a normal git server and cloned remotely because `git-upload-pack` doesn't recognise it:

```
$ git-upload-pack --strict x.git
fatal: 'x.git' does not appear to be a git repository
```

**Comment by olsen232** [comment]
Fixed at https://github.com/koordinates/sno/commit/c34605663b0ff7b218e6c89305ecacd91aba0302

Sno 0.5 - all sno repos are "bare-style" repos

Sno as of https://github.com/koordinates/sno/commit/3d1b1902eea79ad88c1a3e25152b2e393f567836 - all new repos are "new n tidy" / "tidy-style" repos. All existing repos are still "old and bare" / "bare-style" unless upgraded.

Sno as of https://github.com/koordinates/sno/commit/c34605663b0ff7b218e6c89305ecacd91aba0302 - new bare repos are "bare-style", new repos with working copy are "tidy-style". All existing repos are still "bare-style" unless upgraded. No longer referring to different styles as "new" or "old"

Sno 0.6 - presumably the same.
