### ISSUE TITLE
Look into timestamptz vs timestamp.

### ISSUE THREAD

**Issue by olsen232** [koordinates/sno#310]
All GPKG timestamps are in UTC. They look like this: "2020-31-12T01:02:03Z"

PostGIS has a type TIMESTAMPTZ that means "a timestamp with a timezone". (This doesn't mean a timestamp with any timezone - notably, you can't use this type to store that event E happened "at time T in timezone TZ". All TIMESTAMPTZ's are stored in UTC. You can easily find out when they happened in a timezone of your choice, but you can't store a timezone of your choice in the database). Since this type works the same as the GPKG type, it makes sense right now that PostGIS code uses TIMESTAMPTZ where GPKG uses TIMESTAMP, both behave exactly the same.

There is another type PostGIS TIMESTAMP that stores exactly the same information, but doesn't assume that the timestamp is in any particular timezone, so no conversion to any other timezone is possible. In python terms, these are naive timestamps. We currently don't use these anywhere, and they are a somewhat less useful / more error-prone type than TIMESTAMPTZ.

The original datasets V2 spec planned to support timestamps both with and without timezone, but not a lot of specifics. We could approximate TIMESTAMP WITHOUT TZ as just a TIMESTAMP in GPKG, and because a GPKG TIMESTAMP is actually just a string, we could leave off the "Z" suffix to the values written in GPKG to indicate that it is a naive timestamp.

The spec indicated that in schema.json, timestamp columns should have a "timezone" attribute - in the spec, this seems to be either true/false, or contain a string like "Pacific Daylight Time". However, since the two flavours of timestamp we can support are either "definitely UTC" or "might be any timezone", I recommend we call this attribute "UTC" and give it two values - "UTC": True or "UTC": null. (Currently, null attributes can be omitted, so not specifying "UTC":True would mean the timestamp is naive).

Currently there is no way to import things as TIMESTAMP WITHOUT TZ. Not sure if OGR gives us enough information to make this call. If we can't find a way to import TIMESTAMP WITHOUT TZ, then supporting them at all seems pretty low priority - it will be pretty rare that someone imports data with timestamps and then specifically changes them to TIMESTAMP WITHOUT TZ by editing the schema.

**Comment by rcoup** [comment]
ok, so maybe we drop TIMESTAMP WITHOUT TZ for now?

**Comment by olsen232** [comment]
Punted for now. I'll start a doc for tracking known issues of low priority, since they're kind of cluttering up the issue tracker right now.
