### ISSUE TITLE
Similar work...

### ISSUE THREAD

**Issue by saberraz** [koordinates/sno#33]
Not really an issue but, we have a similar project for data (sqlite based at the moment) tracking and versioning:
https://github.com/lutraconsulting/geodiff

And we have a QGIS plugin with web platform (not open source) around it 
https://public.cloudmergin.com/
https://github.com/lutraconsulting/qgis-mergin-plugin

The Geodiff library is used in Input app: 
https://github.com/lutraconsulting/input

Happy to run a demo of the web platform if you are interested....

**Comment by rcoup** [comment]
@saberraz thanks! We're working through improved diffs and merging at the moment and we'll certainly have a look at geodiff's approach 👍
