### ISSUE TITLE
create-workingcopy: InsufficientPrivilege errors when creating schema

### ISSUE THREAD

**Issue by craigds** [koordinates/sno#391]
I called `sno create-workingcopy` from a bare repo with a postgres URL. I got this:

```
Traceback (most recent call last):
  File "site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
  File "site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
psycopg2.errors.InsufficientPrivilege: permission denied for database <dbname>
```

It's right - it doesn't have the permissions to create a schema, but this schema already exists (it was created by the superuser already for this purpose).

It shoudl probably check if the schema already exists and then not try to create it.

**Comment by olsen232** [comment]
:( apparently `CREATE SCHEMA IF NOT EXISTS` errors if the schema exists but you don't have permission to create it. That's sad. I'll fix it.

**Comment by olsen232** [comment]
Fixed at https://github.com/koordinates/sno/commit/3c730b6a97e451370ab805da57d70b28e7ea3a9a
