### ISSUE TITLE
Define a sane behaviour for `..` and `...` in refspecs

### ISSUE THREAD

**Issue by craigds** [koordinates/sno#51]
## Git behaviour:

In git-land, `..` and `...` are pretty confusing.

git log and git diff treat them differently/oppositely: https://stackoverflow.com/a/463027/988527

sno should... not do that :)

## Current sno behaviour 

* `sno log` currently just passes refspecs directly to `git log`, so see ^
* `sno diff` treats `..` and `...` as synonyms, but doesn't implement diffs of commits where one commit is not an ancestor of the other.

## Proposed behaviour

I propose we always stick to the `git log` approach (`..` means an asymmetric difference, `...` means a symmetric difference) for both commands.

This approach makes sense if you consider the commit graph

```
A     C
 \   /
  \ /
   B
```

* `sno diff a..c` should be equivalent to the diff between `b` and `c` - the contents of `a` are not taken into account, so only two endpoints are relevant, hence there are two dots.
* `sno diff a...c` should be equivalent to the sum of the diff between `a` and `b` _plus_ the diff between `b` and `c`. There are three endpoints that are relevant, hence the three dots.

Obviously this is subjective, however treating the two differently in the two commands is a really bizarre behaviour of git that trips lots of people up, so let's avoid doing that by defining a saner behaviour now

**Comment by rcoup** [comment]
> git log and git diff treat them differently/oppositely:
> sno should... not do that :)

100x yes.

> `sno diff a..c` should be equivalent to the diff between b and c - the contents of a are not taken into account, so only two endpoints are relevant, hence there are two dots.

do you mean "between a and c - the contents of b are not taken into account" ?

**Comment by craigds** [comment]
> do you mean "between a and c - the contents of b are not taken into account" ?

nope - `a..c` is a diff between:
- the merge-base of a and c (i.e. b)
- c

another way of thinking of it is "the sum of all commits that are in `c` that are not in `a`". It doesn't include changes that are `a` that aren't in `c`.

**Comment by rcoup** [comment]
so one-way `a..c` vs two-way `a...c`?

**Comment by craigds** [comment]
I personally find the words 'one-way' and 'two-way' just as confusing

`a...c` is a diff that you could apply to `a` to end up with the same tree as `c`.

`a..c` is _not_ that; it may not apply to `a` at all because `a` may have other changes that conflict with the changes in `a..c`. However `a..c` is a very useful way of seeing "what did branch `c` actually change, since branch `a` diverged from it?"
