### ISSUE TITLE
Don't use GeoJSON for geometry representations in diffs

### ISSUE THREAD

**Issue by craigds** [koordinates/sno#62]
(Extracting this discussion from https://github.com/koordinates/sno/pull/61#discussion_r414505669 )

Currently, JSON diffs and patches from sno represent geometries as GeoJSON.

However, GeoJSON doesn't support curved geometries, which means we won't support the full simple features spec.

Whatever we use:
 * should support empty geometries, circular geometries, and geometry collections
 * doesn't need to include CRS information (that's a layer-level concern, doesn't need to be included on each feature)

Obvious alternatives include:

* WKT
* Hex-encoded WKB
* some other encoding of WKB (e.g. base64). (Non-standard, but 50% more compact than hex-encoded)

Notes:

* WKT has the advantage of being somewhat human-readable.
* WKB has the advantage of being lossless, and _also_ not requiring parsing in some situations (i.e. we can read straight from PostGIS/GPKG and encode in hex without going through OGR)

I suggest we use hex-encoded WKB since I don't think anyone cares much about readability of geometry blobs, and I don't think the 50% size reduction of base64-encoding is worth being different to everyone else.

**Comment by rcoup** [comment]
* The `geojson` diff format should be standard GeoJSON — it's used for all sorts of things, I think the benefits outweigh any other concerns. I think if a Curve/etc is encountered we just bail.
* Within reason, `json` we can do whatever we like with. But we're encoding as GeoJSON-style features at the moment, so...

> WKB has the advantage of being lossless

WKT/GeoJSON is lossless with [17 significant figures](https://stackoverflow.com/a/8990831/2662).

> I don't think the 50% size reduction of base64-encoding is worth being different to everyone else.

Agree

My preference is probably hex-encoded hex-encoded ISO WKB, but I wonder whether WKT or GeoJSON support is more than a trivial extension? Since correct WKB encoding/decoding can be a major pain depending on platform/language/tools. 

Maybe something like this so it's extensible? Dunno how we advertise what diff format it is though? `"sno.diff/v1/wkb"` or `"geometry@wkb": ...`?

```js
{
  "geometry": {
    // as GeoJSON
    "type": "Point"
    "coordinates": [
      175.54948977028008,
      -36.675330575884495
    ],
    // or as WKB
    "wkb": "...",
    // or as WKT
    "wkt": "...",
  },
  "id": "U-::1095",
  "properties": {
    "fid": 1095,
    "macronated": "Y",
    "name": "Harataunga (Rākairoa)\n",
    "name_ascii": "Harataunga (Rakairoa)\n",
    "t50_fid": 2427339
  },
  "type": "Feature"
},
```
  
Other thing is whether we add builtin compression? These things are gonna be big, and as you say, aren't usually humanly meaningful.  

eg:
```console
$ sno diff -z -f a.diff.gz ...
$ sno diff -J -f a.diff.xz ...

$ sno apply a.diff.xz
```
```

**Comment by craigds** [comment]
> something like this so it's extensible

it's trivial for a parser to inspect and differentiate geojson/WKT/WKB:

```python
if not g:
    # null
elif isinstance(g, dict):
    # geojson
elif g[0].isdigit():
    # hexWKB
else:
    # WKT 
```

So if those are our only options ever, there's no need to put them in an object and key by type. Just spec that you can use whichever you want, and the parser can figure it out.

That said, I'd only bother making it handle the ones we need _now_ (I'd say just hexWKB, because no one has patches yet so we don't need to support GeoJSON)

**Comment by craigds** [comment]
> Since correct WKB encoding/decoding can be a major pain depending on platform/language/tools.

Could you expand on that? It's not a particularly complicated structure

**Comment by craigds** [comment]
> Other thing is whether we add builtin compression? These things are gonna be big, and as you say, aren't usually humanly meaningful.

:+1: Definitely

**Comment by craigds** [comment]
> WKT/GeoJSON is lossless with 17 significant figures.

With that in mind the main advantage of using hexWKB would be being able to translate these things direct from the repo structure where they're stored as WKB, without passing through OGR. But I'd be happy with WKT too, whichever.

**Comment by rcoup** [comment]
> Could you expand on that? It's not a particularly complicated structure

_for example_, browser JS doesn't have native IEEE754 parsing, so you have to implement _that_. Even if you get past that there are a pile of WKB edge cases to handle (Z/M/EMPTY/endianness). Nobody is going to parse WKB in a JS script to extract X&Y from a point compared with doing `mypoint = feature.geometry.coordinates` with GeoJSON.

**Comment by rcoup** [comment]
```python
elif g[0].isdigit():
    # hexWKB
```

So relying on the first byte being the endian-ness indicator?

**Comment by rcoup** [comment]
> That said, I'd only bother making it handle the ones we need now (I'd say just hexWKB, because no one has patches yet so we don't need to support GeoJSON)

sure, except this needs to be consistent across diff/patch/apply

**Comment by craigds** [comment]
> ```python
> elif g[0].isdigit():
>     # hexWKB
> ```
> 
> So relying on the first byte being the endian-ness indicator?

Not sure what this means quite. The first byte of actual WKB is the byte order marker, and has a value of either 0 or 1. So in hex WKB that byte is split into two characters, and the first character is always `0` (the second byte is either `0` or `1`).

So `elif g[0].isdigit():` could equally be written `if g[0] == '0'`; I don't think any other digit there is valid.

Contrast with WKT - the first byte is always a letter (`POINT...` or `POLYGON...` etc)

**Comment by rcoup** [comment]
To me, "is it a `0` or a dict or `A-Z`?" seems like a completely janky way of determining what format it is. _And_ it's per-feature, so you might be reading 1000s of features before you get a geometry change and only then realise you can't parse it.

I think indicating upfront that any/all geometries are WKB or GeoJSON or WKT is clean and simplifies a whole lot. At the cost of a few bytes at the start of the file.

**Comment by craigds** [comment]
> I think indicating upfront that any/all geometries are WKB or GeoJSON or WKT is clean and simplifies a whole lot.

I think I disagree - one fairly simple `if` statement keeps geometry parsing fully local to a `parse_geometry` method. You're suggesting that instead, we make the patch application code pass `geometry_format='geojson'` down through several frames, just so the geometry parser can reject things  it could otherwise handle perfectly well.

> At the cost of a few bytes at the start of the file

Our json diff format doesn't leave a great deal of room for specifying metadata like this. The child objects under `sno.diff/v1` are datasets, so seems like the wrong place. We could encode this into the top level key I guess? `sno.diff/v1+hexwkb`. but it feels pretty weird to me. It makes patch parsing a bit more annoying too - you have to iterate over all the keys and see if they match a whitelist, rather than just look for the one you know will be there (though we'll have to do something like that for versioning sooner or later anyway I suppose)

**Comment by craigds** [comment]
> you might be reading 1000s of features before you get a geometry change and only then realise you can't parse it.

you mean if the parser didn't support the type of features in the patch? pretty niche case - since patches are machine-generated in general I'd expect all features in one patch will be the same format. We shouldn't optimise for this.

**Comment by rcoup** [comment]
> we make the patch application code pass geometry_format='geojson' down through several frames, just so the geometry parser can reject things it could otherwise handle perfectly well.

Totally happy for it to be implemented _internally_ as an `if` statement in `parse_geometry()`, but that's a horrible format/external interface

> Our json diff format doesn't leave a great deal of room for specifying metadata like this.

We could fix this 😄 

> since patches are machine-generated in general I'd expect all features in one patch will be the same format

Agreed, but there could very easily be a huge number of null-geometries before any actual data is encountered.

**Comment by rcoup** [comment]
> you have to iterate over all the keys and see if they match a whitelist

`re.match("sno.diff/v1(?:\+(?P<geom_format>hexwkb|geojson|wkt))?$", key)`?

**Comment by craigds** [comment]
okay, so using `"sno.diff/v1+hexwkb"` is fine and doesn't require any other changes... For now no patches will contain any other kind of geometry; this is purely a future-compatibility change.

I won't bother supporting `"sno.diff/v1"` (geojson) patches, because no one has patches yet. In future we can add them back in with `"sno.diff/v1+geojson"` if required.
