### ISSUE TITLE
Rename meta tables in geopackage to `gpkg_*`

### ISSUE THREAD

**Issue by craigds** [koordinates/sno#63]
When dragging a sno working copy GPKG into QGIS, you're presented with this dialog:

<img width="696" alt="Screen Shot 2020-04-30 at 7 52 39 AM" src="https://user-images.githubusercontent.com/32112/80641445-ff4be180-8ab8-11ea-94eb-03a789dd1b0f.png">

OGR does similar:

```bash
$ ogrinfo -ro points.gpkg
INFO: Open of `points.gpkg'
      using driver `GPKG' successful.
1: nz_pa_points_topo_150k (Point)
2: .sno-meta (None)
3: .sno-track (None)
```

It'd be best if we could hide those .sno tables. We could just rename them to `gpkg_sno_track` and `gpkg_sno_meta` and OGR/QGIS would ignore them:

```
$ sqlite3 points2.gpkg
SQLite version 3.28.0 2019-04-15 14:49:49
Enter ".help" for usage hints.
sqlite> alter table `.sno-meta` rename to `gpkg_sno_meta`;
sqlite> alter table `.sno-track` rename to `gpkg_sno_track`;


$ ogrinfo -ro points2.gpkg
INFO: Open of `points2.gpkg'
      using driver `GPKG' successful.
1: nz_pa_points_topo_150k (Point)
```

**Comment by rcoup** [comment]
Should probably [register Sno into `gpkg_extensions`](http://www.geopackage.org/spec/#_extensions) for GPKG working copies as well, that'd allow QGIS/GDAL/something to know it's related to Sno.
