### ISSUE TITLE
Internal data format revision (v2)

### ISSUE THREAD

**Issue by rcoup** [koordinates/sno#72]
There are a number of issues with the current internal repo dataset structure which need addressing. Most of which are hangovers from the original proofs-of-concept. 

[This document discusses the problems and a proposed solution](https://docs.google.com/document/d/1C-WodV9DV2gCenDynaapdzgyV4EBc9rQtovOiTqLWiU/edit?usp=sharing) (comments open)

It'll be backwards incompatible, so we'll need an upgrade process & scripts in place.

**Comment by craigds** [comment]
This is reasonably concrete now. We should document the implemented format. The above google doc is missing the later additions (legends)

**Comment by rcoup** [comment]
Can we move it into a markdown doc in the source tree?

**Comment by craigds** [comment]
IMO restructuredtext because we'll have a proper readthedocs build going sooner or later and rst is more useful for that

**Comment by olsen232** [comment]
Closing this bug since v2 is mostly done - anything missing should be filed more specifically
