### ISSUE TITLE
Tracking - pygit2 FRs / issues

### ISSUE THREAD

**Issue by olsen232** [koordinates/sno#79]
These are actually issues / FRs in pygit2. If any of these issues are also being tracked there, please add a link here to the pygit2 issue.

So far, most of them can be worked around in sno, probably with less effort than fixing them would be in pygit2 (particularly those which involve both python and C changes). But, here they are, for tracking purposes. If they are fixed in pygit2, we can perhaps remove some code from sno.

1. Missing function Repository.state()
git_repository_state available in libgit2 but not exposed by pygit2.
Contains logic like "if exists: GIT_DIR/GIT_MERGE_HEAD_FILE then: state = MERGING

2. Rename conflicts aren't properly exposed (no work around)
pygit2.Index conflicts doesn't expose rename information, opting instead to give each version of a file its own conflict tuple if it doesn't share a file name with any other version of the same file. The following merge result is ambiguous:
```
>>> pygit2.Index.conflicts
[ ("a.txt", None, None), ("b.txt", None, None), (None, "c.txt", None), (None, "d.txt", None), (None, None, "e.txt"), (None, None, "f.txt")]
```
(Brief explanation - a file with only one version suggests an add or a delete, except an add or delete would not be a conflict. The fact that these are showing up in conflicts indicates that libgit2 detected rename conflicts - perhaps "a.txt" was renamed to both "c.txt" and "e.txt" - but because there is more than one conflict and no rename info is exposed, it is impossible to know what actually conflicts with what and why.)

3. pygit2.Index could be more user friendly -
- can't save it to an arbitrary file, or write it as a tree to an arbitrary repo, doesn't support == or repr()

4. pygit2.IndexEntry could be more user friendly -
- doesn't support == or repr()

5. repo.resolve_refish doc suggests that it returns commits, but it can also return other pygit2 objects.

**Comment by rcoup** [comment]
I think these should mostly be ticketed upstream, but just seeking some clarifications:

> 3) pygit2.Index could be more user friendly -
> can't save it to an arbitrary file, or write it as a tree to an arbitrary repo, doesn't support == or repr()

Do you know if libgit2 supports writing?

> 2) Rename conflicts aren't properly exposed (no work around)

Does Libgit2 expose this? (ie. it's an issue with the pygit2 side, or a bigger task)

**Comment by olsen232** [comment]
3. writing pygit2.Index to arbitrary file
libgit2 definitely supports writing the index to the file it was read from, and probably supports writing to an arbitrary file if we can change the value of the C-string at index->index_file_path. So it would require either no change or a small plumbing change to libgit2.

2. Rename conflicts aren't properly exposed
Hard to say what is required. The result of a merge operation in C is just a huge list of index entries - all with path, blob-ID, and file-mode data, and also with a flag set that marks them as either successfully merged, or one of 3 versions - ancestor, ours, theirs.
The conflicts collection exposed in python is generated by zipping together all 3 conflict versions, keyed by path. So, if the paths don't match, they no longer line up. So, the current strategy is not promising - big changes are needed at least in pygit2 - but its not clear to me if the only way to access conflicts in libgit2 is by path, or if there is another way of getting the information we need.

I did write "no work around" - information is lost in the API that we cannot currently recover - but its not quite true, there are actually some work arounds:
- we can (probably) turn off rename detection entirely, so that everything is an add, edit, or delete. This also makes merge conflicts fewer, and easier to deal with. Possibly we should do this in the interim anyway.
- we can (probably) turn off inexact rename detection, so that only renames that are not also edits are detected as such
- we can (probably) detect exact renames at the python level by just checking the blob-ID of resulting Index

**Comment by olsen232** [comment]
6. Python API doesn't let you customise merge options for merge_commits and merge_trees, except you can choose the "favor". You can't, for example, turn GIT_MERGE_FIND_RENAMES on or off except by accessing the code at a lower level

**Comment by olsen232** [comment]
1. Missing function Repository.state()
Still not done, but perhaps not actually that useful to us - even if pygit2 told us we were in state MERGING, we would still need to look at the files ourselves to gather the necessary context.

2. Rename conflicts aren't properly exposed.
Not done, will be lots of work. But with 6 now done, at least we can turn off rename detection until and unless we can fix renames to work better.

3. pygit2.Index could be more user friendly -
Not done, but now we have our own structure MergeIndex that is backed by a pygit2.Index, but also supports writing conflicts or conflict resolutions to the index. Since writing conflict resolutions to the index is beyond the scope of pygit2.Index, we probably will continue to use MergeIndex, so changing pygit2.Index isn't really needed.

4. pygit2.IndexEntry could be more user friendly -
Done at https://github.com/libgit2/pygit2/commit/2b5602bbae79c485b92c18e3bef40548b6282d13

5. repo.resolve_refish doc suggests that it returns commits, but it can also return other pygit2 objects
Not done

6. Python API doesn't let you customise merge options.
Done at https://github.com/libgit2/pygit2/commit/ded6a322e88fd5fa489f3fcf081e9cecd16e0ddb
