### ISSUE TITLE
Building from source per instructions requires jq

### ISSUE THREAD

**Issue by hamishcampbell** [koordinates/sno#81]
Platform: MacOS.

Build notes in [CONTRIBUTING.md](https://github.com/koordinates/sno/blob/bbe48edb16b0437f899655d2e315f8acbec729a5/CONTRIBUTING.md) list the following prerequisites:

  - Python 3.7
  - wget
  - cmake

However building on MacOS reports:

```
sno $ make
/Library/Developer/CommandLineTools/usr/bin/make -C vendor all
/Library/Developer/CommandLineTools/usr/bin/make dist/vendor-Darwin.tar.gz
/Library/Developer/CommandLineTools/usr/bin/make download
./github-download.sh
❗️This script requires 'jq' (and ideally 'hub') installed
make[3]: *** [download] Error 2
make[2]: *** [dist/vendor-Darwin.tar.gz] Error 2
make[1]: *** [all] Error 2
make: *** [vendor/dist/vendor-Darwin.tar.gz] Error 2
```

This is fixed with `brew install jq`

Unsure if an how other platforms are impacted.

**Comment by rcoup** [comment]
Added note to docs in 772b80ef

Note for future-readers: `jq` is used by the vendor dependencies download script to skip building the dependencies, which can take A Very Long Time. Full build from source with `make -C vendor build-{Darwin,Linux}`, then continue with `make`
